#!/usr/bin/env node
// Fetch a Google Fonts css2 stylesheet and inline every woff2 as a data URI,
// keeping only the subsets we need (default: thai,latin). Output is a single
// fonts.css with no external requests — required for claude.ai artifact
// preview (CSP blocks font CDNs) and makes shipped sites load with zero
// round-trips. Variable-font files that repeat across weights are embedded
// once with a min–max font-weight range.
//
// Usage: node tools/fetch-fonts.mjs "<css2-url>" <out.css> [subsets]
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const [, , cssUrl, outPath, subsetArg = 'thai,latin'] = process.argv;
if (!cssUrl || !outPath) {
  console.error('usage: fetch-fonts.mjs <css2-url> <out.css> [subsets=thai,latin]');
  process.exit(1);
}
const wanted = new Set(subsetArg.split(','));
// woff2 is only served to browsers that advertise support
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';
const css = execSync(`curl -sf --max-time 30 -H 'User-Agent: ${UA}' '${cssUrl}'`, { encoding: 'utf8' });

const blocks = [...css.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]+\})/g)].filter(m => wanted.has(m[1]));
if (blocks.length === 0) {
  console.error('no @font-face blocks matched the requested subsets — check the URL');
  process.exit(1);
}

const byUrl = new Map();
for (const [, subset, block] of blocks) {
  const family = block.match(/font-family: '([^']+)'/)[1];
  const weight = Number(block.match(/font-weight: (\d+)/)[1]);
  const url = block.match(/src: url\(([^)]+)\)/)[1];
  const range = block.match(/unicode-range: ([^;]+);/)[1];
  const key = `${family}|${subset}|${url}`;
  const entry = byUrl.get(key) ?? { family, subset, url, range, weights: [] };
  entry.weights.push(weight);
  byUrl.set(key, entry);
}

let out = '/* generated by tools/fetch-fonts.mjs — do not edit by hand */\n';
for (const e of byUrl.values()) {
  const b64 = execSync(`curl -sf --max-time 60 '${e.url}' | base64 -w0`, {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  }).trim();
  const lo = Math.min(...e.weights);
  const hi = Math.max(...e.weights);
  const weight = lo === hi ? `${lo}` : `${lo} ${hi}`;
  out += `/* ${e.family} ${weight} ${e.subset} */
@font-face {
  font-family: '${e.family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url(data:font/woff2;base64,${b64}) format('woff2');
  unicode-range: ${e.range};
}
`;
}
writeFileSync(outPath, out);
console.log(`${outPath}: ${byUrl.size} faces, ${(out.length / 1024).toFixed(0)} KB`);
